#!/usr/bin/env python3
"""Build the Joke Machine web page from jokes.json.

Reads jokes.json, writes docs/index.html. Run it after editing the jokes.

    python3 build_site.py
"""

import html
import json
import pathlib

HERE = pathlib.Path(__file__).parent
DATA = HERE / "jokes.json"
OUT = HERE / "docs" / "index.html"

PAGE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>
:root {{
  --bg: #faf8f4;
  --card: #ffffff;
  --ink: #1b1a17;
  --muted: #6b6357;
  --gold: #cfb991;
  --line: #e4ddd0;
}}
@media (prefers-color-scheme: dark) {{
  :root {{
    --bg: #171613;
    --card: #23211d;
    --ink: #f2efe8;
    --muted: #a79c8a;
    --gold: #cfb991;
    --line: #38342c;
  }}
}}
* {{ box-sizing: border-box; }}
body {{
  margin: 0;
  padding: 32px 20px 64px;
  background: var(--bg);
  color: var(--ink);
  font: 17px/1.55 -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
}}
.wrap {{ max-width: 760px; margin: 0 auto; }}
h1 {{
  font-size: 2.4rem;
  margin: 0 0 6px;
  letter-spacing: -0.02em;
}}
.tagline {{ color: var(--muted); margin: 0 0 18px; }}
#sound {{
  font: inherit;
  font-size: .92rem;
  color: var(--ink);
  background: var(--card);
  border: 1px solid var(--line);
  border-radius: 999px;
  padding: 7px 16px;
  cursor: pointer;
  margin-bottom: 26px;
}}
#sound:hover {{ border-color: var(--gold); }}
.grid {{
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
  gap: 12px;
  margin-bottom: 28px;
}}
button.cat {{
  font: inherit;
  font-weight: 600;
  color: var(--ink);
  background: var(--card);
  border: 1px solid var(--line);
  border-radius: 12px;
  padding: 16px 12px;
  cursor: pointer;
  transition: transform .08s ease, border-color .15s ease;
}}
button.cat:hover {{ border-color: var(--gold); }}
button.cat:active {{ transform: scale(.97); }}
button.cat[aria-pressed="true"] {{
  border-color: var(--gold);
  box-shadow: inset 0 0 0 2px var(--gold);
}}
button.cat .emoji {{ display: block; font-size: 1.7rem; margin-bottom: 6px; }}
#stage {{
  background: var(--card);
  border: 1px solid var(--line);
  border-left: 5px solid var(--gold);
  border-radius: 12px;
  padding: 26px 24px;
  min-height: 120px;
  display: flex;
  flex-direction: column;
  justify-content: center;
}}
#topic {{
  font-size: .78rem;
  letter-spacing: .09em;
  text-transform: uppercase;
  color: var(--muted);
  margin-bottom: 10px;
}}
#joke {{ font-size: 1.22rem; margin: 0; cursor: pointer; }}
#again {{
  font: inherit;
  margin-top: 20px;
  align-self: flex-start;
  background: var(--gold);
  color: #1b1a17;
  border: 0;
  border-radius: 9px;
  padding: 10px 20px;
  font-weight: 600;
  cursor: pointer;
}}
#again[hidden] {{ display: none; }}
footer {{ color: var(--muted); font-size: .85rem; margin-top: 34px; }}
</style>
</head>
<body>
<div class="wrap">
  <h1>{title}</h1>
  <p class="tagline">{tagline}</p>

  <button id="sound" type="button" aria-pressed="true">🔊 Read jokes out loud</button>

  <div class="grid" id="grid"></div>

  <div id="stage">
    <div id="topic"></div>
    <p id="joke">Pick a topic above.</p>
    <button id="again" hidden>Another one</button>
  </div>
  <p id="novoice" class="tagline" hidden>This browser cannot read text out loud.</p>

  <footer>Built for ECE 60141 Lab 1. Page generated by <code>build_site.py</code>.</footer>
</div>

<script>
const DATA = {data};

const grid    = document.getElementById("grid");
const topic   = document.getElementById("topic");
const joke    = document.getElementById("joke");
const again   = document.getElementById("again");
const sound   = document.getElementById("sound");
const novoice = document.getElementById("novoice");

let current = null;   // index of the selected category
let bag = [];         // jokes not yet shown for that category

// Read aloud uses the browser's built-in speech synthesis. Nothing is
// downloaded and no account is needed. Older browsers may not have it.
const canSpeak = "speechSynthesis" in window;
let speakOn = canSpeak && localStorage.getItem("speakOn") !== "no";

if (!canSpeak) {{
  sound.hidden = true;
  novoice.hidden = false;
}}

function drawSoundButton() {{
  sound.textContent = speakOn ? "🔊 Read jokes out loud" : "🔇 Sound off";
  sound.setAttribute("aria-pressed", speakOn ? "true" : "false");
}}
drawSoundButton();

function say(text) {{
  if (!speakOn) return;
  speechSynthesis.cancel();            // stop whatever is still talking
  const u = new SpeechSynthesisUtterance(text);
  u.rate = 0.95;
  speechSynthesis.speak(u);
}}

sound.addEventListener("click", () => {{
  speakOn = !speakOn;
  localStorage.setItem("speakOn", speakOn ? "yes" : "no");
  drawSoundButton();
  if (!speakOn) speechSynthesis.cancel();
  else if (current !== null) say(joke.textContent);
}});

// Clicking the joke text repeats it.
joke.addEventListener("click", () => {{ if (current !== null) say(joke.textContent); }});

DATA.categories.forEach((cat, i) => {{
  const b = document.createElement("button");
  b.className = "cat";
  b.type = "button";
  b.setAttribute("aria-pressed", "false");
  b.innerHTML = '<span class="emoji">' + cat.emoji + "</span>" + cat.name;
  b.addEventListener("click", () => pick(i));
  grid.appendChild(b);
}});

// Show a joke from category i. Refill the bag when it runs out, so
// every joke is seen once before any repeats.
function pick(i) {{
  if (i !== current) {{
    current = i;
    bag = [];
    [...grid.children].forEach((b, k) =>
      b.setAttribute("aria-pressed", k === i ? "true" : "false"));
  }}
  if (bag.length === 0) bag = DATA.categories[i].jokes.slice();
  const k = Math.floor(Math.random() * bag.length);
  const text = bag.splice(k, 1)[0];
  topic.textContent = DATA.categories[i].name;
  joke.textContent = text;
  again.hidden = false;
  say(text);
}}

again.addEventListener("click", () => {{ if (current !== null) pick(current); }});
</script>
</body>
</html>
"""


def main():
    data = json.loads(DATA.read_text(encoding="utf-8"))

    n_cats = len(data["categories"])
    n_jokes = sum(len(c["jokes"]) for c in data["categories"])

    page = PAGE.format(
        title=html.escape(data["title"]),
        tagline=html.escape(data["tagline"]),
        data=json.dumps(data, ensure_ascii=False),
    )

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(page, encoding="utf-8")
    print(f"Wrote {OUT}")
    print(f"{n_cats} categories, {n_jokes} jokes.")


if __name__ == "__main__":
    main()
